/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/change-role/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_change_role_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot-password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_forgot_password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /api/auth/logout
         *     - с телом {"refresh": "<token>"}: выход только с текущего устройства
         *     - без тела: выход со всех устройств */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/update/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["auth_me_update_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["auth_me_update_partial_update"];
        trace?: never;
    };
    "/api/auth/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Обновление токенов вручную (альтернатива стандартному TokenRefreshView),
         *     с опциональной ротацией под remember_me.
         *     Body: {"refresh": "<token>", "remember_me": true|false} */
        post: operations["auth_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/resend-verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_resend_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_reset_password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-email/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_verify_email_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/loads/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["loads_retrieve"];
        put: operations["loads_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["loads_partial_update"];
        trace?: never;
    };
    "/api/loads/{id}/cancel/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Отмена активной перевозки:
         *     - право: автор груза ИЛИ назначенный перевозчик
         *     - доступна только для статусов: POSTED, MATCHED
         *     - ставит статус CANCELLED и деактивирует офферы */
        post: operations["loads_cancel_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/loads/{id}/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["loads_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/loads/board/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Борда моих активных заявок.
         *     - select_related('customer')
         *     - offers_active для has_offers
         *     - path_km для price_per_km (фолбэк) */
        get: operations["loads_board_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/loads/create/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["loads_create_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/loads/mine/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description - select_related('customer') для company_name/contact_value
         *     - annotate offers_active для has_offers без N+1
         *     - annotate path_km для расчёта price_per_km (фолбэк) */
        get: operations["loads_mine_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/loads/public/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Публичная доска: видна Перевозчику/Логисту.
         *     Показывает только одобренные, не скрытые и активные заявки.
         *
         *     Поддерживаемые query params:
         *     - origin_city, destination_city, load_date, transport_type, id
         *     - min_weight, max_weight, min_price, max_price, price_currency
         *     - has_offers = true|false
         *     - origin_lat, origin_lng, origin_radius_km
         *     - dest_lat,   dest_lng,   dest_radius_km
         *     - order = path_km|-path_km|origin_dist_km|-origin_dist_km|price_value|-price_value|load_date|-load_date */
        get: operations["loads_public_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/offers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список офферов (видимые текущему пользователю)
         * @description Возвращает офферы, доступные текущему пользователю. Можно уточнить выборку параметром `scope`.
         *
         *     **scope=mine** — как Перевозчик (carrier);
         *     **scope=incoming** — входящие: для Заказчика/Логиста — офферы от перевозчиков; для Перевозчика — инвайты от заказчиков (initiator=CUSTOMER);
         *     **scope=all** — все (только для staff).
         */
        get: operations["offers_list"];
        put?: never;
        /**
         * Создать оффер
         * @description Доступно только Перевозчику/Логисту.
         */
        post: operations["offers_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/offers/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Детали оффера
         * @description Доступно перевозчику-автору, владельцу груза или логиcту.
         */
        get: operations["offers_retrieve"];
        /** @description Эндпоинты:
         *       POST   /api/offers/                  — создать (Перевозчик/Логист)
         *       GET    /api/offers/                  — список, видимый текущему пользователю (scope=…)
         *       GET    /api/offers/my/               — мои офферы как Перевозчик (alias)
         *       GET    /api/offers/incoming/         — входящие (alias): заказчик/логист — офферы от перевозчиков; перевозчик — инвайты
         *       GET    /api/offers/{id}/             — детали
         *       POST   /api/offers/{id}/accept/      — принять
         *       POST   /api/offers/{id}/reject/      — отклонить
         *       POST   /api/offers/{id}/counter/     — контр-предложение
         *       POST   /api/offers/invite/           — инвайт (Заказчик → Перевозчик) */
        put: operations["offers_update"];
        post?: never;
        /** @description Эндпоинты:
         *       POST   /api/offers/                  — создать (Перевозчик/Логист)
         *       GET    /api/offers/                  — список, видимый текущему пользователю (scope=…)
         *       GET    /api/offers/my/               — мои офферы как Перевозчик (alias)
         *       GET    /api/offers/incoming/         — входящие (alias): заказчик/логист — офферы от перевозчиков; перевозчик — инвайты
         *       GET    /api/offers/{id}/             — детали
         *       POST   /api/offers/{id}/accept/      — принять
         *       POST   /api/offers/{id}/reject/      — отклонить
         *       POST   /api/offers/{id}/counter/     — контр-предложение
         *       POST   /api/offers/invite/           — инвайт (Заказчик → Перевозчик) */
        delete: operations["offers_destroy"];
        options?: never;
        head?: never;
        /** @description Эндпоинты:
         *       POST   /api/offers/                  — создать (Перевозчик/Логист)
         *       GET    /api/offers/                  — список, видимый текущему пользователю (scope=…)
         *       GET    /api/offers/my/               — мои офферы как Перевозчик (alias)
         *       GET    /api/offers/incoming/         — входящие (alias): заказчик/логист — офферы от перевозчиков; перевозчик — инвайты
         *       GET    /api/offers/{id}/             — детали
         *       POST   /api/offers/{id}/accept/      — принять
         *       POST   /api/offers/{id}/reject/      — отклонить
         *       POST   /api/offers/{id}/counter/     — контр-предложение
         *       POST   /api/offers/invite/           — инвайт (Заказчик → Перевозчик) */
        patch: operations["offers_partial_update"];
        trace?: never;
    };
    "/api/offers/{id}/accept/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Принять оффер
         * @description Акцепт оффера текущим пользователем. При взаимном акцепте создаётся Shipment.
         */
        post: operations["offers_accept_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/offers/{id}/counter/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Контр-предложение
         * @description Создать контр-предложение. Разрешено владельцу груза или перевозчику этого оффера.
         */
        post: operations["offers_counter_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/offers/{id}/reject/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Отклонить оффер
         * @description Отклонение/снятие оффера любой из сторон. Делает оффер неактивным.
         */
        post: operations["offers_reject_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/offers/incoming/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Входящие офферы / инвайты
         * @description Alias к `GET /api/offers/?scope=incoming`.
         *     Заказчик/Логист — видят офферы от перевозчиков на их заявки.
         *     Перевозчик — видит инвайты от заказчиков (initiator=CUSTOMER).
         */
        get: operations["offers_incoming_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/offers/invite/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Инвайт перевозчику (Заказчик)
         * @description Заказчик отправляет персональное предложение перевозчику на свой груз.
         */
        post: operations["offers_invite_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/offers/my/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Мои офферы (Перевозчик)
         * @description Alias к `GET /api/offers/?scope=mine`.
         */
        get: operations["offers_my_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json */
        get: operations["schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/cargos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search_cargos_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Листинг/борда. Поля рассчитываются так:
         *     - route_km       — по трассе (кэш/провайдер), фолбэк на path_km
         *     - path_km        — приходит из аннотации queryset'а (прямая дистанция в км)
         *     - origin_dist_km — аннотация радиуса (если есть фильтр), иначе None
         *     - has_offers     — активные офферы
         *     - company_name   — берём из профиля заказчика (customer)
         *     - contact_value  — в зависимости от contact_pref (телефон/email/иначе)
         *     - weight_t       — вес в тоннах (из weight_kg)
         *     - price_per_km   — price_value / (route_km или path_km) */
        CargoList: {
            readonly id: number;
            readonly product: string;
            readonly description: string;
            readonly origin_country: string;
            readonly origin_city: string;
            readonly origin_address: string;
            readonly destination_country: string;
            readonly destination_city: string;
            readonly destination_address: string;
            /** Format: date */
            readonly load_date: string;
            /** Format: date */
            readonly delivery_date: string | null;
            readonly transport_type: components["schemas"]["TransportTypeEnum"];
            /** Format: decimal */
            readonly weight_kg: string;
            /** Format: double */
            readonly weight_t: number;
            /** Format: decimal */
            readonly price_value: string | null;
            readonly price_currency: components["schemas"]["PriceCurrencyEnum"];
            readonly contact_pref: components["schemas"]["ContactPrefEnum"];
            readonly contact_value: string;
            readonly is_hidden: boolean;
            readonly company_name: string;
            readonly moderation_status: components["schemas"]["ModerationStatusEnum"];
            readonly status: components["schemas"]["StatusEnum"];
            readonly age_minutes: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly refreshed_at: string;
            readonly has_offers: boolean;
            /** Format: double */
            readonly path_km: number;
            /** Format: double */
            readonly route_km: number | null;
            /**
             * Format: double
             * @description Возвращаем Decimal(2 знака) для денежного значения.
             *     Если дистанция отсутствует или <= 0 — None.
             *     Для дистанции используем приоритет: route_km -> path_km.
             */
            readonly price_per_km: number;
            /** Format: double */
            readonly origin_dist_km: number;
        };
        /** @description Создание/обновление заявки.
         *     - Пользователь вводит только страну/город/адрес (координаты не требуются).
         *     - Сервер сам геокодит и заполняет origin_point/dest_point.
         *     - В ответе отдаём route_km (по трассе), если удалось посчитать/закэшировать. */
        CargoPublish: {
            product: string;
            description?: string;
            origin_country?: string;
            origin_city: string;
            origin_address: string;
            destination_country?: string;
            destination_city: string;
            destination_address: string;
            /** Format: date */
            load_date: string;
            /** Format: date */
            delivery_date?: string | null;
            transport_type: components["schemas"]["TransportTypeEnum"];
            /** Format: decimal */
            weight_kg: string;
            /** Format: decimal */
            price_value?: string | null;
            price_currency?: components["schemas"]["PriceCurrencyEnum"];
            contact_pref: components["schemas"]["ContactPrefEnum"];
            is_hidden?: boolean;
            /** Format: double */
            readonly route_km: number | null;
        };
        /**
         * @description * `email` - Email
         *     * `phone` - Телефон
         *     * `both` - Оба
         * @enum {string}
         */
        ContactPrefEnum: "email" | "phone" | "both";
        ForgotPassword: {
            /** Format: email */
            email: string;
        };
        ForgotPasswordResponse: {
            detail: string;
        };
        /**
         * @description * `CUSTOMER` - Заказчик
         *     * `CARRIER` - Перевозчик
         * @enum {string}
         */
        InitiatorEnum: "CUSTOMER" | "CARRIER";
        Login: {
            login: string;
            password: string;
            /** @default false */
            remember_me: boolean;
        };
        LoginResponse: {
            user: components["schemas"]["Me"];
            access: string;
            refresh: string;
        };
        LogoutRequest: {
            refresh?: string;
        };
        LogoutResponse: {
            detail: string;
        };
        Me: {
            readonly id: number;
            /**
             * Имя пользователя
             * @description Обязательное поле. Не более 150 символов. Только буквы, цифры и символы @/./+/-/_.
             */
            readonly username: string;
            /** Format: email */
            readonly email: string;
            /** Имя */
            first_name?: string;
            phone?: string | null;
            company_name?: string;
            /** Format: uri */
            photo?: string | null;
            readonly role: components["schemas"]["RoleEnum"];
            /** Format: double */
            readonly rating_as_customer: number;
            /** Format: double */
            readonly rating_as_carrier: number;
            readonly is_email_verified: boolean;
        };
        /**
         * @description * `pending` - На модерации
         *     * `approved` - Одобрено
         *     * `rejected` - Отклонено
         * @enum {string}
         */
        ModerationStatusEnum: "pending" | "approved" | "rejected";
        OfferAcceptResponse: {
            detail: string;
            accepted_by_customer: boolean;
            accepted_by_carrier: boolean;
        };
        OfferCounter: {
            /** Format: decimal */
            price_value: string;
            price_currency?: string;
            message?: string;
        };
        /** @description Создание оффера ПЕРЕВОЗЧИКОМ на чужую заявку. */
        OfferCreate: {
            cargo: number;
            /** Format: decimal */
            price_value?: string | null;
            /** @default UZS */
            price_currency: components["schemas"]["PriceCurrencyEnum"];
            message?: string;
        };
        OfferDetail: {
            readonly id: number;
            /** Format: decimal */
            price_value?: string | null;
            price_currency?: components["schemas"]["PriceCurrencyEnum"];
            message?: string;
            readonly accepted_by_customer: boolean;
            readonly accepted_by_carrier: boolean;
            readonly initiator: components["schemas"]["InitiatorEnum"];
            /** @default true */
            readonly is_active: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            cargo: number;
            readonly carrier: number;
        };
        /** @description Создание оффера-ИНВАЙТА ЗАКАЗЧИКОМ конкретному перевозчику. */
        OfferInvite: {
            cargo: number;
            carrier_id: number;
            /** Format: decimal */
            price_value?: string | null;
            /** @default UZS */
            price_currency: components["schemas"]["PriceCurrencyEnum"];
            message?: string;
        };
        OfferRejectResponse: {
            detail: string;
        };
        OfferShort: {
            readonly id: number;
            readonly cargo: number;
            readonly cargo_origin: string;
            readonly cargo_destination: string;
            readonly cargo_customer_id: number;
            /** Format: decimal */
            readonly price_value: string | null;
            readonly price_currency: components["schemas"]["PriceCurrencyEnum"];
            readonly message: string;
            readonly accepted_by_customer: boolean;
            readonly accepted_by_carrier: boolean;
            readonly is_active: boolean;
            /** Format: date-time */
            readonly created_at: string;
        };
        PaginatedCargoListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["CargoList"][];
        };
        PaginatedOfferShortList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["OfferShort"][];
        };
        /** @description Создание/обновление заявки.
         *     - Пользователь вводит только страну/город/адрес (координаты не требуются).
         *     - Сервер сам геокодит и заполняет origin_point/dest_point.
         *     - В ответе отдаём route_km (по трассе), если удалось посчитать/закэшировать. */
        PatchedCargoPublish: {
            product?: string;
            description?: string;
            origin_country?: string;
            origin_city?: string;
            origin_address?: string;
            destination_country?: string;
            destination_city?: string;
            destination_address?: string;
            /** Format: date */
            load_date?: string;
            /** Format: date */
            delivery_date?: string | null;
            transport_type?: components["schemas"]["TransportTypeEnum"];
            /** Format: decimal */
            weight_kg?: string;
            /** Format: decimal */
            price_value?: string | null;
            price_currency?: components["schemas"]["PriceCurrencyEnum"];
            contact_pref?: components["schemas"]["ContactPrefEnum"];
            is_hidden?: boolean;
            /** Format: double */
            readonly route_km?: number | null;
        };
        PatchedOfferDetail: {
            readonly id?: number;
            /** Format: decimal */
            price_value?: string | null;
            price_currency?: components["schemas"]["PriceCurrencyEnum"];
            message?: string;
            readonly accepted_by_customer?: boolean;
            readonly accepted_by_carrier?: boolean;
            readonly initiator?: components["schemas"]["InitiatorEnum"];
            /** @default true */
            readonly is_active: boolean;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            cargo?: number;
            readonly carrier?: number;
        };
        PatchedUpdateMe: {
            /** Имя */
            first_name?: string;
            phone?: string | null;
            company_name?: string;
            /** Format: uri */
            photo?: string | null;
        };
        /**
         * @description * `UZS` - сум
         *     * `KZT` - тнг
         *     * `RUB` - руб
         *     * `USD` - USD
         *     * `EUR` - EUR
         * @enum {string}
         */
        PriceCurrencyEnum: "UZS" | "KZT" | "RUB" | "USD" | "EUR";
        /** @description Простой сериализатор для ответа refresh. */
        RefreshResponse: {
            detail: string;
        };
        Register: {
            /**
             * Имя пользователя
             * @description Обязательное поле. Не более 150 символов. Только буквы, цифры и символы @/./+/-/_.
             */
            username: string;
            /** Format: email */
            email: string;
            password: string;
            password2: string;
            /** Имя */
            first_name?: string;
            phone: string;
            company_name?: string;
            role?: components["schemas"]["RoleEnum"];
        };
        RegisterResponse: {
            detail: string;
        };
        ResendVerify: {
            /** Format: email */
            email: string;
        };
        ResendVerifyResponse: {
            detail: string;
        };
        ResetPassword: {
            /** Format: email */
            email: string;
            code: string;
            new_password: string;
        };
        ResetPasswordResponse: {
            detail: string;
        };
        RoleChange: {
            role: components["schemas"]["RoleEnum"];
        };
        RoleChangeResponse: {
            detail: string;
            role?: string;
        };
        /**
         * @description * `LOGISTIC` - Логист
         *     * `CUSTOMER` - Заказчик
         *     * `CARRIER` - Перевозчик
         * @enum {string}
         */
        RoleEnum: "LOGISTIC" | "CUSTOMER" | "CARRIER";
        /**
         * @description * `POSTED` - Опубликована
         *     * `MATCHED` - В работе
         *     * `DELIVERED` - Доставлено
         *     * `COMPLETED` - Завершено
         *     * `CANCELLED` - Отменена
         * @enum {string}
         */
        StatusEnum: "POSTED" | "MATCHED" | "DELIVERED" | "COMPLETED" | "CANCELLED";
        TokenRefreshRequest: {
            refresh: string;
            remember_me?: boolean;
        };
        TokenRefreshResponse: {
            access: string;
            refresh: string;
        };
        /**
         * @description * `TENT` - Тент
         *     * `CONT` - Контейнер
         *     * `REEFER` - Рефрижератор
         *     * `DUMP` - Самосвал
         *     * `CARTR` - Автотранспортер
         *     * `GRAIN` - Зерновоз
         *     * `LOG` - Лесовоз
         *     * `PICKUP` - Пикап
         *     * `MEGA` - Мега фура
         *     * `OTHER` - Другое
         * @enum {string}
         */
        TransportTypeEnum: "TENT" | "CONT" | "REEFER" | "DUMP" | "CARTR" | "GRAIN" | "LOG" | "PICKUP" | "MEGA" | "OTHER";
        UpdateMe: {
            /** Имя */
            first_name?: string;
            phone?: string | null;
            company_name?: string;
            /** Format: uri */
            photo?: string | null;
        };
        VerifyEmail: {
            /** Format: email */
            email: string;
            code: string;
        };
        VerifyEmailResponse: {
            detail: string;
            access: string;
            refresh: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_change_role_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleChange"];
                "application/x-www-form-urlencoded": components["schemas"]["RoleChange"];
                "multipart/form-data": components["schemas"]["RoleChange"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleChangeResponse"];
                };
            };
        };
    };
    auth_forgot_password_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPassword"];
                "application/x-www-form-urlencoded": components["schemas"]["ForgotPassword"];
                "multipart/form-data": components["schemas"]["ForgotPassword"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForgotPasswordResponse"];
                };
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
                "application/x-www-form-urlencoded": components["schemas"]["Login"];
                "multipart/form-data": components["schemas"]["Login"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LogoutRequest"];
                "multipart/form-data": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    auth_me_update_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateMe"];
                "application/x-www-form-urlencoded": components["schemas"]["UpdateMe"];
                "multipart/form-data": components["schemas"]["UpdateMe"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    auth_me_update_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUpdateMe"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUpdateMe"];
                "multipart/form-data": components["schemas"]["PatchedUpdateMe"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    auth_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefreshResponse"];
                };
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Register"];
                "application/x-www-form-urlencoded": components["schemas"]["Register"];
                "multipart/form-data": components["schemas"]["Register"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
        };
    };
    auth_resend_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendVerify"];
                "application/x-www-form-urlencoded": components["schemas"]["ResendVerify"];
                "multipart/form-data": components["schemas"]["ResendVerify"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResendVerifyResponse"];
                };
            };
        };
    };
    auth_reset_password_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPassword"];
                "application/x-www-form-urlencoded": components["schemas"]["ResetPassword"];
                "multipart/form-data": components["schemas"]["ResetPassword"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetPasswordResponse"];
                };
            };
        };
    };
    auth_verify_email_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmail"];
                "application/x-www-form-urlencoded": components["schemas"]["VerifyEmail"];
                "multipart/form-data": components["schemas"]["VerifyEmail"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyEmailResponse"];
                };
            };
        };
    };
    loads_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CargoPublish"];
                };
            };
        };
    };
    loads_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CargoPublish"];
                "application/x-www-form-urlencoded": components["schemas"]["CargoPublish"];
                "multipart/form-data": components["schemas"]["CargoPublish"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CargoPublish"];
                };
            };
        };
    };
    loads_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCargoPublish"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCargoPublish"];
                "multipart/form-data": components["schemas"]["PatchedCargoPublish"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CargoPublish"];
                };
            };
        };
    };
    loads_cancel_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshResponse"];
                "application/x-www-form-urlencoded": components["schemas"]["RefreshResponse"];
                "multipart/form-data": components["schemas"]["RefreshResponse"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
        };
    };
    loads_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshResponse"];
                "application/x-www-form-urlencoded": components["schemas"]["RefreshResponse"];
                "multipart/form-data": components["schemas"]["RefreshResponse"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
        };
    };
    loads_board_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCargoListList"];
                };
            };
        };
    };
    loads_create_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CargoPublish"];
                "application/x-www-form-urlencoded": components["schemas"]["CargoPublish"];
                "multipart/form-data": components["schemas"]["CargoPublish"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CargoPublish"];
                };
            };
        };
    };
    loads_mine_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCargoListList"];
                };
            };
        };
    };
    loads_public_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCargoListList"];
                };
            };
        };
    };
    offers_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description mine | incoming | all (только staff) */
                scope?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedOfferShortList"];
                };
            };
        };
    };
    offers_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfferCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["OfferCreate"];
                "multipart/form-data": components["schemas"]["OfferCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferDetail"];
                };
            };
        };
    };
    offers_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this offer. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferDetail"];
                };
            };
        };
    };
    offers_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this offer. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfferDetail"];
                "application/x-www-form-urlencoded": components["schemas"]["OfferDetail"];
                "multipart/form-data": components["schemas"]["OfferDetail"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferDetail"];
                };
            };
        };
    };
    offers_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this offer. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    offers_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this offer. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedOfferDetail"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedOfferDetail"];
                "multipart/form-data": components["schemas"]["PatchedOfferDetail"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferDetail"];
                };
            };
        };
    };
    offers_accept_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this offer. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferAcceptResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    offers_counter_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this offer. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfferCounter"];
                "application/x-www-form-urlencoded": components["schemas"]["OfferCounter"];
                "multipart/form-data": components["schemas"]["OfferCounter"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferDetail"];
                };
            };
        };
    };
    offers_reject_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this offer. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferRejectResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    offers_incoming_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedOfferShortList"];
                };
            };
        };
    };
    offers_invite_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfferInvite"];
                "application/x-www-form-urlencoded": components["schemas"]["OfferInvite"];
                "multipart/form-data": components["schemas"]["OfferInvite"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferDetail"];
                };
            };
        };
    };
    offers_my_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedOfferShortList"];
                };
            };
        };
    };
    schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    search_cargos_list: {
        parameters: {
            query?: {
                destination_city?: string;
                origin_city?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCargoListList"];
                };
            };
        };
    };
}
